### ISSUE TITLE
Undefined value parameter

### ISSUE THREAD

**Issue by glittle** [semisleep/simple-vue-validator#1]
I'm getting this error:
```
[Vue warn]: Error in watcher "coords.lat" 
(found in component <Setup> at C:\Users\glen\Source\Repos\Badi-Web3\src\pages\LocationSetup.vue)

VM65704:27 Error: Validator.value not set
    at Rule._checkValue (eval at <anonymous> (http://localhost:8080/js/app.js:1763:1), <anonymous>:42:11)
    at Rule.required (eval at <anonymous> (http://localhost:8080/js/app.js:1763:1), <anonymous>:48:20)
    at VueComponent.coordsLat (eval at <anonymous> (http://localhost:8080/js/app.js:2004:1), <anonymous>:34:37)
    at VueComponent.eval (eval at <anonymous> (http://localhost:8080/js/app.js:2334:1), <anonymous>:41:32)
    at eval (eval at <anonymous> (http://localhost:8080/js/app.js:2334:1), <anonymous>:95:20)
    at Array.map (native)
    at VueComponent.$validate (eval at <anonymous> (http://localhost:8080/js/app.js:2334:1), <anonymous>:94:32)
    at VueComponent.boundFn [as $validate] (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:127:12)
    at VueComponent.checkValidation (eval at <anonymous> (http://localhost:8080/js/app.js:2004:1), <anonymous>:56:12)
    at VueComponent.boundFn [as checkValidation] (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:127:12)
    at VueComponent.coordsLat (eval at <anonymous> (http://localhost:8080/js/app.js:2004:1), <anonymous>:45:12)
    at Watcher.run (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:1735:19)
    at flushSchedulerQueue (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:1539:13)
    at Array.eval (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:471:20)
    at nextTickHandler (eval at <anonymous> (http://localhost:8080/js/app.js:736:1), <anonymous>:420:16)
```

Some extracts from the .vue file:

    <template>
       <input type="number" min="-85" max="85" step="any" v-model="coords.lat" :class="{'has-error': validation.hasError('coords.lat')}">
    </template>
    <script>
     ...
    data() { return coords: {lat: 0, long: 0} },
    validators: {
      'coords.lat': function (value) {
        return Validator.value(value).required().float().between(-85, 85);
      },
      'coords.long': function (value) {
        return Validator.value(value).required().float().between(-180, 180);
      },
    },
    watch: {
      'coords.lat': function (n, o) {
        this.checkValidation()
      },
      'coords.long': function (n, o) {
        this.checkValidation()
      }
    },
    methods: {
      checkValidation() {
        this.$validate()
          .then(function (success) {
            if (success) {
              alert('Validation succeeded!');
            }
          });
      }
    </script>

(The file works fine without validation... the above is a simplified extract to show here.)

The `value` parameter is undefined.   Any ideas why?

If I replace the `return Validator.value(....` with `return true` then I get:

    TypeError: rule.field is not a function

If I entirely remove the `validators: {}` section, then I get a popup with 'Validation succeeded!'.

**Comment by glittle** [comment]
I've rewritten the file and changed `coord.lat` to simply `lat`, but still have the same issue.

**Comment by glittle** [comment]
As is so often the case... it was something else that created the problem. Other code was setting the value of the `data` items to `undefined`... `this.lat = set(50)` where `set` was not returning a value. Once that was fixed up, it seems to be working now.
